In [1]:
import pandas as pd
import numpy as np

In [2]:
def open_csv(file=None,header=6):
    if file:
        #open csv pakai pandas
        data = pd.read_csv(file, header=header)
        #ganti nama header
        data.columns = [
                        "Nama Panggilan", 
                        "Asal Sekolah", 
                        "Jurusan Sekolah", 
                        "Jenis Sekolah",
                        "Jenis Kelas", 
                        "Akreditasi Sekolah", 
                        "Prestasi Sekolah", 
                        "Alumni Sekolah", 
                        "PTN Pilihan I", 
                        "Jurusan Pilihan I di PTN Pilihan I" ,
                        "Jurusan Pilihan II di PTN Pilihan I", 
                        "PTN Pilihan II", 
                        "Jurusan Pilihan I di PTN Pilihan II" ,
                        "Jurusan Pilihan II di PTN Pilihan II", 
                        "Jurusan Diterima", "PTN Diterima", 
                        "Matematika Semester 1", 
                        "Matematika Semester 2", 
                        "Matematika Semester 3", 
                        "Matematika Semester 4", 
                        "Matematika Semester 5", 
                        "Inggris Semester 1", 
                        "Inggris Semester 2", 
                        "Inggris Semester 3", 
                        "Inggris Semester 4", 
                        "Inggris Semester 5",
                        "Indonesia Semester 1",
                        "Indonesia Semester 2",
                        "Indonesia Semester 3",
                        "Indonesia Semester 4",
                        "Indonesia Semester 5",
                        "Fisika Semester 1",
                        "Fisika Semester 2",
                        "Fisika Semester 3",
                        "Fisika Semester 4",
                        "Fisika Semester 5",
                        "Kimia Semester 1",
                        "Kimia Semester 2",
                        "Kimia Semester 3",
                        "Kimia Semester 4",
                        "Kimia Semester 5",
                        "Biologi Semester 1",
                        "Biologi Semester 2",
                        "Biologi Semester 3",
                        "Biologi Semester 4",
                        "Biologi Semester 5",
                        "Ekonomi Semester 1",
                        "Ekonomi Semester 2",
                        "Ekonomi Semester 3",
                        "Ekonomi Semester 4",
                        "Ekonomi Semester 5",
                        "Geografi Semester 1",
                        "Geografi Semester 2",
                        "Geografi Semester 3",
                        "Geografi Semester 4",
                        "Geografi Semester 5",
                        "Sosiologi Semester 1",
                        "Sosiologi Semester 2",
                        "Sosiologi Semester 3",
                        "Sosiologi Semester 4",
                        "Sosiologi Semester 5",
                        "Sejarah Semester 1",
                        "Sejarah Semester 2",
                        "Sejarah Semester 3",
                        "Sejarah Semester 4",
                        "Sejarah Semester 5",
                        "Komputer Semester 1",
                        "Komputer Semester 2",
                        "Komputer Semester 3",
                        "Komputer Semester 4",
                        "Komputer Semester 5",
                        "Peringkat Kelas Semester 1",
                        "Peringkat Kelas Semester 2",
                        "Peringkat Kelas Semester 3",
                        "Peringkat Kelas Semester 4",
                        "Peringkat Kelas Semester 5",
                        "Nilai UN", 
                        "Saran",
                        "Prestasi Lain"
                    ]
        #drop column yang gak digunain
        data = data.drop([
            "Asal Sekolah", 
            "Jenis Kelas",
            "Akreditasi Sekolah", 
            "Prestasi Sekolah", 
            "Alumni Sekolah", 
            "Komputer Semester 1",
            "Komputer Semester 2",
            "Komputer Semester 3",
            "Komputer Semester 4",
            "Komputer Semester 5",
            "Peringkat Kelas Semester 1",
            "Peringkat Kelas Semester 2",
            "Peringkat Kelas Semester 3",
            "Peringkat Kelas Semester 4",
            "Peringkat Kelas Semester 5",
            "Nilai UN", 
            "Saran",
            "Prestasi Lain",
            "Sejarah Semester 1",
            "Sejarah Semester 2",
            "Sejarah Semester 3",
            "Sejarah Semester 4",
            "Sejarah Semester 5",
        ], axis = 1)

        #hapus row jika nama panggilan dan jurusan diterima NaN
        data = data.dropna(subset=["Nama Panggilan"])
    else:
        data = None

    return data

In [3]:
getMapel = lambda columns: {column.split(" Semester ")[0] for column in columns if "Semester" in column}

In [4]:
avg = lambda list_nilai: sum(list_nilai) / len(list_nilai)

In [5]:
def gantiPakeMedian(data):
    #mengambil nilai tengah dari tiap nilai
    data = data.replace("<70", 34.5)
    data = data.replace("71 - 75", 73)
    data = data.replace("76 - 80", 78)
    data = data.replace("81 - 85", 83)
    data = data.replace("86 - 90", 88)
    data = data.replace("91 - 95", 93)
    data = data.replace("> 95", 98)
    data = data.replace("No data", np.NaN)
    
    return data

In [6]:
def getMeanLimaSemester(data, mata_pelajaran, index=0):
    #isi value untuk fillna
    values = dict()
    for i in range(1, 6):
        rata2_per_pelajaran = data[f"{mata_pelajaran} Semester {i}"].mean()
        values[f"{mata_pelajaran} Semester {i}"] = rata2_per_pelajaran

    #isi NaN dengan rata2 semester
    data = data.fillna(value=values)

    #itung rata2 nilai 5 semester
    nilai_siswa_5_semester_list = [data[f"{mata_pelajaran} Semester {idx}"][index] for idx in range(1,6)]
    rata2_nilai_siswa_5_semester = avg(nilai_siswa_5_semester_list)
            
    return rata2_nilai_siswa_5_semester

In [7]:
def getJurusanDiterima(jurusan_diterima):
    if "administrasi" in jurusan_diterima.casefold()\
    or "sosial" in jurusan_diterima.casefold()\
    or "ekonomi" in jurusan_diterima.casefold()\
    or "hi" in jurusan_diterima.casefold()\
    or "hukum" in jurusan_diterima.casefold()\
    or "komunikasi" in jurusan_diterima.casefold()\
    or "politik" in jurusan_diterima.casefold()\
    or "sosiologi" in jurusan_diterima.casefold()\
    or "fsrd" in jurusan_diterima.casefold()\
    or "sbm" in jurusan_diterima.casefold()\
    or "akuntansi" in jurusan_diterima.casefold()\
    or "manajemen" in jurusan_diterima.casefold()\
    or "psdk" in jurusan_diterima.casefold()\
    or "fiskal" in jurusan_diterima.casefold()\
    or ("hubungan" in jurusan_diterima.casefold() and "internasional" in jurusan_diterima.casefold())\
    or "kriminologi" in jurusan_diterima.casefold()\
    or "psikologi" in jurusan_diterima.casefold()\
    or "bisnis" in jurusan_diterima.casefold()\
    or "filsafat" in jurusan_diterima.casefold()\
    or "jurnalistik" in jurusan_diterima.casefold()\
    or "humas" in jurusan_diterima.casefold()\
    or "desain" in jurusan_diterima.casefold()\
    or "film" in jurusan_diterima.casefold()\
    or "antropologi" in jurusan_diterima.casefold()\
    or "keluarga" in jurusan_diterima.casefold()\
    or "konsumen" in jurusan_diterima.casefold()\
    or "sejarah" in jurusan_diterima.casefold()\
    or "menejemen" in jurusan_diterima.casefold()\
    or "arkeologi" in jurusan_diterima.casefold()\
    or ("hubungan" in jurusan_diterima.casefold() and "masyarakat" in jurusan_diterima.casefold())\
    or "akutansi" in jurusan_diterima.casefold():
        jurusan_diterima = f"{jurusan_diterima} (IPS)"
    else:
        jurusan_diterima = f"{jurusan_diterima} (IPA)"

    return jurusan_diterima

In [8]:
def getDictionary(data, mata_pelajaran):
    df = dict()
    df_train_test = dict()
    list_jurusan = set()
    indeks = 0
    for i, row in data.iterrows():
        #dapetin nama jurusan
        jrs = row["Jurusan Diterima"].strip()
        fkl = row["PTN Diterima"].strip()
        jurusan_diterima = f"{jrs} - {fkl}".upper()
        
        #dapetin nama jurusan
        jurusan_diterima = getJurusanDiterima(jurusan_diterima)
        
        if "sastra" not in jurusan_diterima.casefold()\
        and "bahasa" not in jurusan_diterima.casefold()\
        and "perpustakaan" not in jurusan_diterima.casefold()\
        and "ugm" not in jurusan_diterima.casefold():
            list_jurusan.add(jurusan_diterima)
            #masukkin nama panggilan
            if "Nama Panggilan" not in df_train_test:
                df_train_test["Nama Panggilan"] = [row["Nama Panggilan"]]
            else:
                df_train_test["Nama Panggilan"].append(row["Nama Panggilan"])
                
            #masukkin jurusan sekolah
            if "Jurusan Sekolah" not in df_train_test:
                df_train_test["Jurusan Sekolah"] = [row["Jurusan Sekolah"]]
            else:
                df_train_test["Jurusan Sekolah"].append(row["Jurusan Sekolah"])
            
            #masukkin pilihan
            if not pd.isnull(row["PTN Pilihan I"]) and row["PTN Pilihan I"].casefold() != "kosong":
                if "Pilihan I" not in df_train_test:
                    if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan I"]):
                        if row["Jurusan Pilihan I di PTN Pilihan I"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan I"].casefold() != "-":
                            pilihan = getJurusanDiterima(f"{row['Jurusan Pilihan I di PTN Pilihan I'].strip()} - {row['PTN Pilihan I'].strip()}")
                            df_train_test["Pilihan I"] = [pilihan.upper()]
                else:
                    if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan I"]):
                        if row["Jurusan Pilihan I di PTN Pilihan I"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan I"].casefold() != "-":
                            pilihan = getJurusanDiterima(f"{row['Jurusan Pilihan I di PTN Pilihan I'].strip()} - {row['PTN Pilihan I'].strip()}")
                            df_train_test["Pilihan I"].append(pilihan.upper())
                                                          
                if "Pilihan II" not in df_train_test:
                    if not pd.isnull(row["Jurusan Pilihan II di PTN Pilihan I"]):
                        if row["Jurusan Pilihan II di PTN Pilihan I"].casefold() != "kosong" and row["Jurusan Pilihan II di PTN Pilihan I"].casefold() != "-":
                            pilihan = getJurusanDiterima(f"{row['Jurusan Pilihan II di PTN Pilihan I'].strip()} - {row['PTN Pilihan I'].strip()}")
                            df_train_test["Pilihan II"] = [pilihan.upper()]
                        else:
                            df_train_test["Pilihan II"] = ["KOSONG"]
                    else:
                        if not pd.isnull(row["PTN Pilihan II"]):
                            if row["PTN Pilihan II"].casefold() != "kosong":
                                if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan II"]):
                                    if row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "-":
                                        pilihan = getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                        df_train_test["Pilihan II"] = [pilihan.upper()]
                                    else:
                                        df_train_test["Pilihan II"] = ["KOSONG"]
                                else:
                                    df_train_test["Pilihan II"] = ["KOSONG"]
                            else:
                                df_train_test["Pilihan II"] = ["KOSONG"]
                        else:
                            df_train_test["Pilihan II"] = ["KOSONG"]
                else:
                    if not pd.isnull(row["Jurusan Pilihan II di PTN Pilihan I"]):
                        if row["Jurusan Pilihan II di PTN Pilihan I"].casefold() != "kosong" and row["Jurusan Pilihan II di PTN Pilihan I"].casefold() != "-":
                            pilihan = getJurusanDiterima(f"{row['Jurusan Pilihan II di PTN Pilihan I'].strip()} - {row['PTN Pilihan I'].strip()}")
                            df_train_test["Pilihan II"].append(pilihan.upper())
                        else:
                            df_train_test["Pilihan II"].append("KOSONG")
                    else:
                        if not pd.isnull(row["PTN Pilihan II"]):
                            if row["PTN Pilihan II"].casefold() != "kosong" or row["PTN Pilihan II"].casefold() != "-":
                                if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan II"]):
                                    if row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "-":
                                        pilihan = getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                        df_train_test["Pilihan II"].append(pilihan.upper())
                                    else:
                                        df_train_test["Pilihan II"].append("KOSONG")
                                else:
                                    df_train_test["Pilihan II"].append("KOSONG")
                            else:
                                df_train_test["Pilihan II"].append("KOSONG")
                        else:
                            df_train_test["Pilihan II"].append("KOSONG")
                        
            if "Pilihan III" not in df_train_test:
                if not pd.isnull(row["PTN Pilihan II"]):
                    if row["PTN Pilihan II"].casefold() != "kosong" or row["PTN Pilihan II"].casefold() != "-":
                        if df_train_test["Pilihan II"][indeks].casefold() != getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"]} - {row["PTN Pilihan II"]}').casefold():
                            if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan II"]):
                                if row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "-":
                                    pilihan = getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                    df_train_test["Pilihan III"] = [pilihan.upper()]
                                else:
                                    df_train_test["Pilihan III"] = ["KOSONG"]
                            else:
                                df_train_test["Pilihan III"] = ["KOSONG"]
                        else:
                            if not pd.isnull(row["Jurusan Pilihan II di PTN Pilihan II"]):
                                if row["Jurusan Pilihan II di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan II di PTN Pilihan II"].casefold() != "-":
                                    pilihan = getJurusanDiterma(f'{row["Jurusan Pilihan II di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                    df_train_test["Pilihan III"] = [pilihan.upper()]
                                else:
                                    df_train_test["Pilihan III"] = ["KOSONG"]
                            else:
                                df_train_test["Pilihan III"] = ["KOSONG"]
                    else:
                        df_train_test["Pilihan III"] = ["KOSONG"]
                else:
                    df_train_test["Pilihan III"] = ["KOSONG"]
            else:
                if not pd.isnull(row["PTN Pilihan II"]):
                    if row["PTN Pilihan II"].casefold() != "kosong" or row["PTN Pilihan II"].casefold() != "-":
                        if df_train_test["Pilihan II"][indeks].casefold() != getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"]} - {row["PTN Pilihan II"]}').casefold():
                            if not pd.isnull(row["Jurusan Pilihan I di PTN Pilihan II"]):
                                if row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan I di PTN Pilihan II"].casefold() != "-":
                                    pilihan = getJurusanDiterima(f'{row["Jurusan Pilihan I di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                    df_train_test["Pilihan III"].append(pilihan.upper())
                                else:
                                    df_train_test["Pilihan III"].append("KOSONG")
                            else:
                                df_train_test["Pilihan III"].append("KOSONG")
                        else:
                            if not pd.isnull(row["Jurusan Pilihan II di PTN Pilihan II"]):
                                if row["Jurusan Pilihan II di PTN Pilihan II"].casefold() != "kosong" and row["Jurusan Pilihan II di PTN Pilihan II"].casefold() != "-":
                                    pilihan = getJurusanDiterima(f'{row["Jurusan Pilihan II di PTN Pilihan II"].strip()} - {row["PTN Pilihan II"].strip()}')
                                    df_train_test["Pilihan III"].append(pilihan.upper())
                                else:
                                    df_train_test["Pilihan III"].append("KOSONG")
                            else:
                                df_train_test["Pilihan III"].append("KOSONG")
                    else:
                        df_train_test["Pilihan III"].append("KOSONG")
                else:
                    df_train_test["Pilihan III"].append("KOSONG")
            
            indeks += 1
                                                                        
            #masukkin jurusan diterima
            if "Jurusan Diterima" not in df_train_test:
                df_train_test["Jurusan Diterima"] = [jurusan_diterima]
            else:
                df_train_test["Jurusan Diterima"].append(jurusan_diterima)
        
            #bikin dictionary untuk data frame
            mean_list_temp = list()
            for item in mata_pelajaran:
                #masukkin mata pelajaran
                if item not in df_train_test:
                    df_train_test[item] = [getMeanLimaSemester(data, item, i)]
                else: 
                    df_train_test[item].append(getMeanLimaSemester(data, item, i))
                    
                if jurusan_diterima not in df:
                    df[jurusan_diterima] = [[getMeanLimaSemester(data, item, i)]]
                else:
                    if len(df[jurusan_diterima][0]) >= 9:
                        mean_list_temp.append(getMeanLimaSemester(data, item, i))
                        if len(mean_list_temp) >= 9:
                            df[jurusan_diterima].append(mean_list_temp)
                            del mean_list_temp
                    else:
                        df[jurusan_diterima][0].append(getMeanLimaSemester(data, item, i))

    #rata2in value di dictionary
    for item in list_jurusan:
        if len(df[item]) > 1:
            df[item] = [sum(x)/len(df[item]) for x in zip(*df[item])]
        else:
            df[item] = df[item][0]
    
                                                                            
    return [df, df_train_test]

In [9]:
data = open_csv("data/Data SNMPTN 2016 ITB by @halokampus.csv")

In [10]:
data

,Nama Panggilan,Jurusan Sekolah,Jenis Sekolah,PTN Pilihan I,Jurusan Pilihan I di PTN Pilihan I,Jurusan Pilihan II di PTN Pilihan I,PTN Pilihan II,Jurusan Pilihan I di PTN Pilihan II,Jurusan Pilihan II di PTN Pilihan II,Jurusan Diterima,...,Geografi Semester 1,Geografi Semester 2,Geografi Semester 3,Geografi Semester 4,Geografi Semester 5,Sosiologi Semester 1,Sosiologi Semester 2,Sosiologi Semester 3,Sosiologi Semester 4,Sosiologi Semester 5
0,Nadija,IPA,SMA,ITB,STEI,kosong,kosong,kosong,kosong,STEI,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
1,Diah,IPA,SMA,ITB,Fakultas Teknik Industri,NaN,KOSONG,NaN,NaN,Fakultas Teknik Industri,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ihsan,IPA,SMA,ITB,FITB,FTTM,KOSONG,NaN,NaN,FITB,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
3,Riana,IPA,SMA,ITB,SITH-Sains,SITH-Rekayasa,ITS,Teknik Lingkungan,NaN,SITH-Sains,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nisrin,IPA,SMA,ITB,Fakultas teknik industri - kampus ganesha,Fakultas teknik mesin dan dirgantara,KOSONG,NaN,NaN,Fakultas teknik mesin dan dirgantara,...,No data,No data,No data,No data,No data,81 - 85,86 - 90,No data,No data,No data
5,"Safira, fira",IPA,SMA,ITB,FSRD,Kosong,Kosong,Kosong,Kosong,FSRD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Satrio,IPA,SMA,ITB,FITB,FTSL-Ganesha,KOSONG,NaN,NaN,FITB,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
7,Ari,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
8,Resty,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Choiza,IPA,SMA,ITB,FTI,TEKNIK KIMIA,UGM,TEKNIK MESIN,TEKNIK FISIKA,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Iky,IPA,SMA,ITB,FTI - G,FTSL,ITB,NaN,NaN,FTI - G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Li atau Nel,IPA,SMA,ITB,STEI,FMIPA,Kosong,Kosong,Kosong,STEI,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
12,Raihan,IPA,SMA,ITB,STEI,SAPPK,KOSONG,NaN,NaN,STEI,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
13,Sodiko,IPA,SMA,ITB,Sekolah Bisnis & Manajemen,NaN,KOSONG,NaN,NaN,Sekolah Bisnis & Manajemen,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
14,Ica,IPA,SMA,ITB,fmipa,NaN,KOSONG,NaN,NaN,fmipa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Boti,IPA,SMA,Itb,Fmipa,NaN,KOSONG,NaN,NaN,Fmipa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Alif,IPA,SMA,ITB,Teknik Mesin,NaN,KOSONG,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Nanda,IPA,SMA,ITB,FMIPA,NaN,ITS,Matematika,Statistika,FMIPA,...,NaN,NaN,NaN,NaN,NaN,No data,No data,No data,No data,No data
18,Syams,IPA,SMA,Itb,Ftsl,Fmipa,Unpad,Matematika,NaN,Ftsl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Oji,IPA,SMA,ITB,SAPPK,SITH,USU,Akuntansi,-,SAPPK,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
20,Dinan,IPA,SMA,ITB,SAPPK,NaN,KOSONG,NaN,NaN,SAPPK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Debora,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Dito,IPA,SMA,ITB,FTI,FMIPA,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Grace,IPA,SMA,ITB,Matematika (Fak. Matematika & Ilmu Pengetahuan...,kosong,kosong,kosong,kosong,Matematika (Fak. Matematika & Ilmu Pengetahuan...,...,71 - 75,81 - 85,No data,No data,No data,81 - 85,86 - 90,No data,No data,No data
24,Nasya,IPA,SMA,ITB,FTTM,Perencanaan Wilayah dan Kota,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Lean,IPA,SMA,ITB,FTTM,Teknik Industri,UNS,Kedokteran,NaN,FTTM,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
26,Iim,IPA,SMA,ITB,FMIPA,SITH-R,ITS,Statistika,NaN,FMIPA,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
27,Ardi,IPA,SMA,ITB,FTI,FTTM,UI,Teknik Kimia,Kosong,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Oktada,IPA,SMA,ITB,FTTM,FTMD,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Aji,IPA,SMA,ITB,Fakultas Ilmu dan Teknologi Kebumian,Sekolah Arsitektur Perencanaan dan Pengembanga...,ITS,Teknik Geomatika,Kosong,Fakultas Ilmu dan Teknologi Kebumian,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
30,Mayang,IPA,SMA,ITB,SAPPK - Peminatan Perencanaan Wilayah Kota Kel...,FITB,KOSONG,NaN,NaN,SAPPK - Peminatan Perencanaan Wilayah Kota Kel...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Sheila,IPA,SMA,ITB,FMIPA,SF,kosong,kosong,kosong,FMIPA,...,81 - 85,81 - 85,71 - 75,71 - 75,71 - 75,86 - 90,86 - 90,No data,No data,No data
32,Kelvin,IPA,SMA,ITB,FMIPA,NaN,UNPAD,Fisika,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Edo,IPA,SMA,ITB,FTI,NaN,KOSONG,NaN,NaN,FTI,...,86 - 90,86 - 90,86 - 90,91 - 95,> 95,No data,No data,No data,No data,No data
34,Fara,IPA,SMA,ITB,FITB,FMIPA,UB,ILMU GIZI,NaN,FITB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Gerry,IPA,SMA,ITB,FMIPA,FTSL,KOSONG,NaN,NaN,FMIPA,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
36,Adita,IPA,SMA,ITB,Sekolah Bisnis dan Manajemen (SBM),Sekolah Teknik Elektro dan Informatika (STEI),UI,Manajemen,NaN,Sekolah Bisnis dan Manajemen (SBM),...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
37,Athira,IPA,SMA,ITB,FTI,Kosong,Kosong,Kosong,Kosong,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Refanie,IPA,SMA,ITB,Fakultas Teknologi Industri,Sekolah Farmasi,UI,Farmasi,Kosong,Fakultas Teknologi Industri,...,81 - 85,91 - 95,91 - 95,86 - 90,81 - 85,No data,No data,No data,No data,No data
39,Muthia,IPA,SMA,ITB,SITH-Program Rekayasa,Kosong,IPB,Manajemen Hutan,Kosong,SITH-Program Rekayasa,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
40,Niel,IPA,SMA,ITB,FTMD,SAPPK,KOSONG,NaN,NaN,FTMD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Dicta,IPA,SMA,ITB,FTTM,NaN,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Luthfan,IPA,SMA,ITB,FMIPA,Kosong,Kosong,Kosong,Kosong,FMIPA,...,81 - 85,76 - 80,No data,No data,No data,76 - 80,76 - 80,No data,No data,No data
43,Kevin,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
44,Faiz,IPA,SMA,ITB,SBM,SITH,KOSONG,NaN,NaN,SBM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Arina,IPA,SMA,Itb,Arsitektur,Sbm,KOSONG,NaN,NaN,Arsitektur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Marha,IPA,SMA,ITB,FTI - MRI,SF,KOSONG,NaN,NaN,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Iffa,IPA,SMA,ITB,STEI,FTTM,UI,Sistem informasi,kosong,STEI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Junius,IPA,SMA,ITB,FTMD,FTSL-G,UI,Farmasi,-,FTMD,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
49,Jacob,IPA,SMA,Itb,Ftsl,Fakultas teknik arsitek,Ui,Teknik sipil,Kosong,Ftsl,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data
50,Erlien,IPA,SMA,Itb,Elektro,Geologi,Ui,Teknik industri,Teknik elektro,Elektro,...,86 - 90,86 - 90,86 - 90,86 - 90,86 - 90,NaN,NaN,NaN,NaN,NaN
51,Rifia,IPA,SMA,ITB,Fakultas Teknik Sipil dan Lingkungan,Sekolah Arsitektur Perencanaan dan Pengembanga...,KOSONG,NaN,NaN,Fakultas Teknik Sipil dan Lingkungan,...,No data,No data,No data,No data,No data,No data,No data,No data,No data,No data

In [11]:
data = gantiPakeMedian(data)

In [12]:
data

,Nama Panggilan,Jurusan Sekolah,Jenis Sekolah,PTN Pilihan I,Jurusan Pilihan I di PTN Pilihan I,Jurusan Pilihan II di PTN Pilihan I,PTN Pilihan II,Jurusan Pilihan I di PTN Pilihan II,Jurusan Pilihan II di PTN Pilihan II,Jurusan Diterima,...,Geografi Semester 1,Geografi Semester 2,Geografi Semester 3,Geografi Semester 4,Geografi Semester 5,Sosiologi Semester 1,Sosiologi Semester 2,Sosiologi Semester 3,Sosiologi Semester 4,Sosiologi Semester 5
0,Nadija,IPA,SMA,ITB,STEI,kosong,kosong,kosong,kosong,STEI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Diah,IPA,SMA,ITB,Fakultas Teknik Industri,NaN,KOSONG,NaN,NaN,Fakultas Teknik Industri,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ihsan,IPA,SMA,ITB,FITB,FTTM,KOSONG,NaN,NaN,FITB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Riana,IPA,SMA,ITB,SITH-Sains,SITH-Rekayasa,ITS,Teknik Lingkungan,NaN,SITH-Sains,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nisrin,IPA,SMA,ITB,Fakultas teknik industri - kampus ganesha,Fakultas teknik mesin dan dirgantara,KOSONG,NaN,NaN,Fakultas teknik mesin dan dirgantara,...,NaN,NaN,NaN,NaN,NaN,83.0,88.0,NaN,NaN,NaN
5,"Safira, fira",IPA,SMA,ITB,FSRD,Kosong,Kosong,Kosong,Kosong,FSRD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Satrio,IPA,SMA,ITB,FITB,FTSL-Ganesha,KOSONG,NaN,NaN,FITB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Ari,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Resty,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Choiza,IPA,SMA,ITB,FTI,TEKNIK KIMIA,UGM,TEKNIK MESIN,TEKNIK FISIKA,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Iky,IPA,SMA,ITB,FTI - G,FTSL,ITB,NaN,NaN,FTI - G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Li atau Nel,IPA,SMA,ITB,STEI,FMIPA,Kosong,Kosong,Kosong,STEI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Raihan,IPA,SMA,ITB,STEI,SAPPK,KOSONG,NaN,NaN,STEI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Sodiko,IPA,SMA,ITB,Sekolah Bisnis & Manajemen,NaN,KOSONG,NaN,NaN,Sekolah Bisnis & Manajemen,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Ica,IPA,SMA,ITB,fmipa,NaN,KOSONG,NaN,NaN,fmipa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Boti,IPA,SMA,Itb,Fmipa,NaN,KOSONG,NaN,NaN,Fmipa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Alif,IPA,SMA,ITB,Teknik Mesin,NaN,KOSONG,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Nanda,IPA,SMA,ITB,FMIPA,NaN,ITS,Matematika,Statistika,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Syams,IPA,SMA,Itb,Ftsl,Fmipa,Unpad,Matematika,NaN,Ftsl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Oji,IPA,SMA,ITB,SAPPK,SITH,USU,Akuntansi,-,SAPPK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Dinan,IPA,SMA,ITB,SAPPK,NaN,KOSONG,NaN,NaN,SAPPK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Debora,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Dito,IPA,SMA,ITB,FTI,FMIPA,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Grace,IPA,SMA,ITB,Matematika (Fak. Matematika & Ilmu Pengetahuan...,kosong,kosong,kosong,kosong,Matematika (Fak. Matematika & Ilmu Pengetahuan...,...,73.0,83.0,NaN,NaN,NaN,83.0,88.0,NaN,NaN,NaN
24,Nasya,IPA,SMA,ITB,FTTM,Perencanaan Wilayah dan Kota,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Lean,IPA,SMA,ITB,FTTM,Teknik Industri,UNS,Kedokteran,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Iim,IPA,SMA,ITB,FMIPA,SITH-R,ITS,Statistika,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Ardi,IPA,SMA,ITB,FTI,FTTM,UI,Teknik Kimia,Kosong,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Oktada,IPA,SMA,ITB,FTTM,FTMD,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Aji,IPA,SMA,ITB,Fakultas Ilmu dan Teknologi Kebumian,Sekolah Arsitektur Perencanaan dan Pengembanga...,ITS,Teknik Geomatika,Kosong,Fakultas Ilmu dan Teknologi Kebumian,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Mayang,IPA,SMA,ITB,SAPPK - Peminatan Perencanaan Wilayah Kota Kel...,FITB,KOSONG,NaN,NaN,SAPPK - Peminatan Perencanaan Wilayah Kota Kel...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Sheila,IPA,SMA,ITB,FMIPA,SF,kosong,kosong,kosong,FMIPA,...,83.0,83.0,73.0,73.0,73.0,88.0,88.0,NaN,NaN,NaN
32,Kelvin,IPA,SMA,ITB,FMIPA,NaN,UNPAD,Fisika,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Edo,IPA,SMA,ITB,FTI,NaN,KOSONG,NaN,NaN,FTI,...,88.0,88.0,88.0,93.0,98.0,NaN,NaN,NaN,NaN,NaN
34,Fara,IPA,SMA,ITB,FITB,FMIPA,UB,ILMU GIZI,NaN,FITB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Gerry,IPA,SMA,ITB,FMIPA,FTSL,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Adita,IPA,SMA,ITB,Sekolah Bisnis dan Manajemen (SBM),Sekolah Teknik Elektro dan Informatika (STEI),UI,Manajemen,NaN,Sekolah Bisnis dan Manajemen (SBM),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Athira,IPA,SMA,ITB,FTI,Kosong,Kosong,Kosong,Kosong,FTI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Refanie,IPA,SMA,ITB,Fakultas Teknologi Industri,Sekolah Farmasi,UI,Farmasi,Kosong,Fakultas Teknologi Industri,...,83.0,93.0,93.0,88.0,83.0,NaN,NaN,NaN,NaN,NaN
39,Muthia,IPA,SMA,ITB,SITH-Program Rekayasa,Kosong,IPB,Manajemen Hutan,Kosong,SITH-Program Rekayasa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Niel,IPA,SMA,ITB,FTMD,SAPPK,KOSONG,NaN,NaN,FTMD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Dicta,IPA,SMA,ITB,FTTM,NaN,KOSONG,NaN,NaN,FTTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Luthfan,IPA,SMA,ITB,FMIPA,Kosong,Kosong,Kosong,Kosong,FMIPA,...,83.0,78.0,NaN,NaN,NaN,78.0,78.0,NaN,NaN,NaN
43,Kevin,IPA,SMA,ITB,FMIPA,NaN,KOSONG,NaN,NaN,FMIPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Faiz,IPA,SMA,ITB,SBM,SITH,KOSONG,NaN,NaN,SBM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Arina,IPA,SMA,Itb,Arsitektur,Sbm,KOSONG,NaN,NaN,Arsitektur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Marha,IPA,SMA,ITB,FTI - MRI,SF,KOSONG,NaN,NaN,SF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Iffa,IPA,SMA,ITB,STEI,FTTM,UI,Sistem informasi,kosong,STEI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Junius,IPA,SMA,ITB,FTMD,FTSL-G,UI,Farmasi,-,FTMD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Jacob,IPA,SMA,Itb,Ftsl,Fakultas teknik arsitek,Ui,Teknik sipil,Kosong,Ftsl,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Erlien,IPA,SMA,Itb,Elektro,Geologi,Ui,Teknik industri,Teknik elektro,Elektro,...,88.0,88.0,88.0,88.0,88.0,NaN,NaN,NaN,NaN,NaN
51,Rifia,IPA,SMA,ITB,Fakultas Teknik Sipil dan Lingkungan,Sekolah Arsitektur Perencanaan dan Pengembanga...,KOSONG,NaN,NaN,Fakultas Teknik Sipil dan Lingkungan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
mata_pelajaran = getMapel(data)

In [14]:
df_table = getDictionary(data, mata_pelajaran)[0]

In [15]:
df_test_train = getDictionary(data, mata_pelajaran)[1]

In [16]:
table_alternatif = pd.DataFrame(df_table, list(mata_pelajaran))

In [17]:
table_alternatif

,STEI - ITB (IPA),FAKULTAS TEKNIK INDUSTRI - ITB (IPA),FITB - ITB (IPA),SITH-SAINS - ITB (IPA),FAKULTAS TEKNIK MESIN DAN DIRGANTARA - ITB (IPA),FSRD - ITB (IPS),FMIPA - ITB (IPA),FTI - ITB (IPA),FTI - G - ITB (IPA),SEKOLAH BISNIS & MANAJEMEN - ITB (IPS),...,SAPPK - PEMINATAN PERENCANAAN WILAYAH KOTA KELAS GANESHA - ITB (IPA),SEKOLAH BISNIS DAN MANAJEMEN (SBM) - ITB (IPS),FAKULTAS TEKNOLOGI INDUSTRI - ITB (IPA),SITH-PROGRAM REKAYASA - ITB (IPA),FTMD - ITB (IPA),SBM - ITB (IPS),ARSITEKTUR - ITB (IPA),SF - ITB (IPA),ELEKTRO - ITB (IPA),FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN - ITB (IPA)
Biologi,88.250000,84.703232,85.000000,87.000000,85.0,84.703232,81.354592,88.175808,82.000000,81.0,...,90.000000,83.000000,90.000000,88.0,92.000000,84.703232,86.000000,90.000000,87.000000,85.000000
Ekonomi,84.060065,84.655844,84.655844,84.655844,88.0,84.655844,84.570430,85.474026,84.655844,85.0,...,84.655844,84.655844,84.655844,90.0,84.655844,84.655844,84.655844,84.655844,84.655844,84.655844
Inggris,89.250000,84.080000,86.666667,96.000000,82.0,86.648293,82.853321,91.162073,79.000000,85.0,...,91.000000,86.000000,86.000000,87.0,92.500000,86.648293,90.000000,93.000000,91.000000,90.000000
Sosiologi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fisika,87.500000,86.538782,87.333333,87.000000,85.0,86.538782,84.701257,92.634696,87.000000,84.0,...,86.538782,85.000000,95.000000,91.0,93.500000,86.538782,86.000000,86.000000,84.000000,87.451282
Geografi,85.000000,85.000000,85.000000,85.000000,85.0,85.000000,84.269231,86.500000,85.000000,85.0,...,85.000000,85.000000,88.000000,85.0,85.000000,85.000000,85.000000,85.000000,88.000000,85.000000
Indonesia,87.000000,85.207317,89.000000,83.000000,90.0,85.207317,81.393996,86.301829,83.000000,78.0,...,85.000000,85.000000,86.000000,90.0,88.500000,85.207317,91.000000,92.000000,86.000000,87.000000
Kimia,90.000000,87.548780,85.666667,90.000000,88.0,87.548780,86.549719,93.387195,91.000000,78.0,...,86.000000,85.000000,85.000000,91.0,92.500000,87.548780,88.000000,86.000000,85.000000,88.000000
Matematika,89.000000,86.995122,88.000000,84.000000,91.0,77.000000,85.883114,91.748780,87.000000,87.0,...,79.000000,93.000000,86.000000,89.0,92.000000,86.995122,89.000000,81.000000,85.000000,88.000000

In [18]:
train = pd.DataFrame(df_test_train)

In [19]:
train

,Nama Panggilan,Jurusan Sekolah,Pilihan I,Pilihan II,Pilihan III,Jurusan Diterima,Biologi,Ekonomi,Inggris,Sosiologi,Fisika,Geografi,Indonesia,Kimia,Matematika
0,Nadija,IPA,STEI - ITB (IPA),KOSONG,KOSONG,STEI - ITB (IPA),85.000000,84.655844,90.000000,NaN,87.000000,85.0,85.000000,92.00000,92.000000
1,Diah,IPA,FAKULTAS TEKNIK INDUSTRI - ITB (IPA),KOSONG,KOSONG,FAKULTAS TEKNIK INDUSTRI - ITB (IPA),84.703232,84.655844,84.080000,NaN,86.538782,85.0,85.207317,87.54878,86.995122
2,Ihsan,IPA,FITB - ITB (IPA),FTTM - ITB (IPA),KOSONG,FITB - ITB (IPA),81.000000,84.655844,87.000000,NaN,89.000000,85.0,89.000000,83.00000,93.000000
3,Riana,IPA,SITH-SAINS - ITB (IPA),SITH-REKAYASA - ITB (IPA),TEKNIK LINGKUNGAN - ITS (IPA),SITH-SAINS - ITB (IPA),87.000000,84.655844,96.000000,NaN,87.000000,85.0,83.000000,90.00000,84.000000
4,Nisrin,IPA,FAKULTAS TEKNIK INDUSTRI - KAMPUS GANESHA - IT...,FAKULTAS TEKNIK MESIN DAN DIRGANTARA - ITB (IPA),KOSONG,FAKULTAS TEKNIK MESIN DAN DIRGANTARA - ITB (IPA),85.000000,88.000000,82.000000,NaN,85.000000,85.0,90.000000,88.00000,91.000000
5,"Safira, fira",IPA,FSRD - ITB (IPS),KOSONG,KOSONG,FSRD - ITB (IPS),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,77.000000
6,Satrio,IPA,FITB - ITB (IPA),FTSL-GANESHA - ITB (IPA),KOSONG,FITB - ITB (IPA),86.000000,84.655844,83.000000,NaN,85.000000,85.0,85.000000,86.00000,87.000000
7,Ari,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),91.000000,87.928571,86.648293,NaN,93.000000,85.0,93.000000,98.00000,93.000000
8,Resty,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),34.500000,84.655844,34.500000,NaN,34.500000,85.0,34.500000,34.50000,34.500000
9,Choiza,IPA,FTI - ITB (IPA),TEKNIK KIMIA - ITB (IPA),TEKNIK MESIN - UGM (IPA),FTI - ITB (IPA),91.000000,84.655844,97.000000,NaN,97.000000,85.0,84.000000,98.00000,92.000000
10,Iky,IPA,FTI - G - ITB (IPA),FTSL - ITB (IPA),KOSONG,FTI - G - ITB (IPA),82.000000,84.655844,79.000000,NaN,87.000000,85.0,83.000000,91.00000,87.000000
11,Li atau Nel,IPA,STEI - ITB (IPA),FMIPA - ITB (IPA),KOSONG,STEI - ITB (IPA),93.000000,81.000000,93.000000,NaN,93.000000,85.0,88.000000,95.00000,92.000000
12,Raihan,IPA,STEI - ITB (IPA),SAPPK - ITB (IPA),KOSONG,STEI - ITB (IPA),88.000000,85.928571,89.000000,NaN,88.000000,85.0,85.000000,85.00000,91.000000
13,Sodiko,IPA,SEKOLAH BISNIS & MANAJEMEN - ITB (IPS),KOSONG,KOSONG,SEKOLAH BISNIS & MANAJEMEN - ITB (IPS),81.000000,85.000000,85.000000,NaN,84.000000,85.0,78.000000,78.00000,87.000000
14,Ica,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
15,Boti,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),76.000000,84.655844,81.000000,NaN,85.000000,85.0,78.000000,95.00000,84.000000
16,Alif,IPA,TEKNIK MESIN - ITB (IPA),KOSONG,KOSONG,0 - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
17,Nanda,IPA,FMIPA - ITB (IPA),MATEMATIKA - ITS (IPA),STATISTIKA - ITS (IPA),FMIPA - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
18,Syams,IPA,FTSL - ITB (IPA),FMIPA - ITB (IPA),MATEMATIKA - UNPAD (IPA),FTSL - ITB (IPA),86.732500,84.655844,91.000000,NaN,90.000000,85.0,90.000000,87.00000,93.000000
19,Oji,IPA,SAPPK - ITB (IPA),SITH - ITB (IPA),AKUNTANSI - USU (IPS),SAPPK - ITB (IPA),91.000000,84.655844,88.000000,NaN,81.000000,85.0,92.000000,89.00000,85.000000
20,Dinan,IPA,SAPPK - ITB (IPA),KOSONG,KOSONG,SAPPK - ITB (IPA),89.000000,84.655844,89.000000,NaN,82.000000,85.0,87.000000,85.00000,86.000000
21,Debora,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),89.000000,84.655844,85.000000,NaN,89.000000,85.0,84.000000,88.00000,93.000000
22,Dito,IPA,FTI - ITB (IPA),FMIPA - ITB (IPA),KOSONG,FMIPA - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
23,Grace,IPA,MATEMATIKA (FAK. MATEMATIKA & ILMU PENGETAHUAN...,KOSONG,KOSONG,MATEMATIKA (FAK. MATEMATIKA & ILMU PENGETAHUAN...,85.000000,83.500000,87.000000,NaN,90.000000,82.5,82.000000,88.00000,90.000000
24,Nasya,IPA,FTTM - ITB (IPA),PERENCANAAN WILAYAH DAN KOTA - ITB (IPA),KOSONG,FTTM - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
25,Lean,IPA,FTTM - ITB (IPA),TEKNIK INDUSTRI - ITB (IPA),KEDOKTERAN - UNS (IPA),FTTM - ITB (IPA),84.000000,77.000000,85.000000,NaN,93.000000,85.0,86.000000,88.00000,89.000000
26,Iim,IPA,FMIPA - ITB (IPA),SITH-R - ITB (IPA),STATISTIKA - ITS (IPA),FMIPA - ITB (IPA),87.000000,84.655844,90.000000,NaN,90.000000,85.0,93.000000,93.00000,90.000000
27,Ardi,IPA,FTI - ITB (IPA),FTTM - ITB (IPA),TEKNIK KIMIA - UI (IPA),FTI - ITB (IPA),87.000000,84.655844,89.000000,NaN,89.000000,85.0,89.000000,96.00000,96.000000
28,Oktada,IPA,FTTM - ITB (IPA),FTMD - ITB (IPA),KOSONG,FTTM - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
29,Aji,IPA,FAKULTAS ILMU DAN TEKNOLOGI KEBUMIAN - ITB (IPA),SEKOLAH ARSITEKTUR PERENCANAAN DAN PENGEMBANGA...,TEKNIK GEOMATIKA - ITS (IPA),FAKULTAS ILMU DAN TEKNOLOGI KEBUMIAN - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
30,Mayang,IPA,SAPPK - PEMINATAN PERENCANAAN WILAYAH KOTA KEL...,FITB - ITB (IPA),KOSONG,SAPPK - PEMINATAN PERENCANAAN WILAYAH KOTA KEL...,90.000000,84.655844,91.000000,NaN,86.538782,85.0,85.000000,86.00000,79.000000
31,Sheila,IPA,FMIPA - ITB (IPA),SF - ITB (IPA),KOSONG,FMIPA - ITB (IPA),82.000000,82.000000,89.000000,NaN,94.000000,77.0,87.000000,91.00000,95.000000
32,Kelvin,IPA,FMIPA - ITB (IPA),FISIKA - UNPAD (IPA),KOSONG,FMIPA - ITB (IPA),86.000000,84.655844,90.000000,NaN,91.000000,85.0,86.000000,94.00000,86.995122
33,Edo,IPA,FTI - ITB (IPA),KOSONG,KOSONG,FTI - ITB (IPA),90.000000,87.928571,92.000000,NaN,98.000000,91.0,87.000000,92.00000,92.000000
34,Fara,IPA,FITB - ITB (IPA),FMIPA - ITB (IPA),ILMU GIZI - UB (IPA),FITB - ITB (IPA),88.000000,84.655844,90.000000,NaN,88.000000,85.0,93.000000,88.00000,84.000000
35,Gerry,IPA,FMIPA - ITB (IPA),FTSL - ITB (IPA),KOSONG,FMIPA - ITB (IPA),84.000000,84.655844,88.000000,NaN,91.000000,85.0,83.000000,92.00000,93.000000
36,Adita,IPA,SEKOLAH BISNIS DAN MANAJEMEN (SBM) - ITB (IPS),SEKOLAH TEKNIK ELEKTRO DAN INFORMATIKA (STEI) ...,MANAJEMEN - UI (IPS),SEKOLAH BISNIS DAN MANAJEMEN (SBM) - ITB (IPS),83.000000,84.655844,86.000000,NaN,85.000000,85.0,85.000000,85.00000,93.000000
37,Athira,IPA,FTI - ITB (IPA),KOSONG,KOSONG,FTI - ITB (IPA),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
38,Refanie,IPA,FAKULTAS TEKNOLOGI INDUSTRI - ITB (IPA),SEKOLAH FARMASI - ITB (IPA),FARMASI - UI (IPA),FAKULTAS TEKNOLOGI INDUSTRI - ITB (IPA),90.000000,84.655844,86.000000,NaN,95.000000,88.0,86.000000,85.00000,86.000000
39,Muthia,IPA,SITH-PROGRAM REKAYASA - ITB (IPA),KOSONG,MANAJEMEN HUTAN - IPB (IPS),SITH-PROGRAM REKAYASA - ITB (IPA),88.000000,90.000000,87.000000,NaN,91.000000,85.0,90.000000,91.00000,89.000000
40,Niel,IPA,FTMD - ITB (IPA),SAPPK - ITB (IPA),KOSONG,FTMD - ITB (IPA),93.000000,84.655844,92.000000,NaN,94.000000,85.0,91.000000,95.00000,93.000000
41,Dicta,IPA,FTTM - ITB (IPA),KOSONG,KOSONG,FTTM - ITB (IPA),78.000000,84.655844,81.000000,NaN,80.000000,85.0,88.000000,79.00000,81.000000
42,Luthfan,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),88.000000,82.928571,89.000000,NaN,81.000000,83.5,85.000000,86.00000,93.000000
43,Kevin,IPA,FMIPA - ITB (IPA),KOSONG,KOSONG,FMIPA - ITB (IPA),86.000000,84.655844,84.000000,NaN,93.000000,85.0,79.000000,91.00000,93.000000
44,Faiz,IPA,SBM - ITB (IPS),SITH - ITB (IPA),KOSONG,SBM - ITB (IPS),84.703232,84.655844,86.648293,NaN,86.538782,85.0,85.207317,87.54878,86.995122
45,Arina,IPA,ARSITEKTUR - ITB (IPA),SBM - ITB (IPS),KOSONG,ARSITEKTUR - ITB (IPA),86.000000,84.655844,90.000000,NaN,86.000000,85.0,91.000000,88.00000,89.000000
46,Marha,IPA,FTI - MRI - ITB (IPA),SF - ITB (IPA),KOSONG,SF - ITB (IPA),90.000000,84.655844,93.000000,NaN,86.000000,85.0,92.000000,86.00000,81.000000
47,Iffa,IPA,STEI - ITB (IPA),FTTM - ITB (IPA),SISTEM INFORMASI - UI (IPA),STEI - ITB (IPA),87.000000,84.655844,85.000000,NaN,82.000000,85.0,90.000000,88.00000,81.000000
48,Junius,IPA,FTMD - ITB (IPA),FTSL-G - ITB (IPA),FARMASI - UI (IPA),FTMD - ITB (IPA),91.000000,84.655844,93.000000,NaN,93.000000,85.0,86.000000,90.00000,91.000000
49,Jacob,IPA,FTSL - ITB (IPA),FAKULTAS TEKNIK ARSITEK - ITB (IPA),TEKNIK SIPIL - UI (IPA),FTSL - ITB (IPA),61.600000,84.655844,81.000000,NaN,63.600000,85.0,78.000000,82.00000,74.300000
50,Erlien,IPA,ELEKTRO - ITB (IPA),GEOLOGI - ITB (IPA),TEKNIK INDUSTRI - UI (IPA),ELEKTRO - ITB (IPA),87.000000,84.655844,91.000000,NaN,84.000000,88.0,86.000000,85.00000,85.000000
51,Rifia,IPA,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN - ITB (IPA),SEKOLAH ARSITEKTUR PERENCANAAN DAN PENGEMBANGA...,KOSONG,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN - ITB (IPA),85.000000,84.655844,90.000000,NaN,87.451282,85.0,87.000000,88.00000,88.000000