In [1]:
import pandas as pd
import math
import numpy as np

# Open File

Membuka file dataset dengan ekstensi **csv**. Setelah itu merename nama-nama header. Baru kemudian men-drop column-column yang tidak akan digunakan.

In [2]:
def open_file(file):
    #read dataset
    raw_data = pd.read_csv(file, header=6)

    #ganti nama header
    raw_data.columns = [
                        "Nama Panggilan", 
                        "Asal Sekolah", 
                        "Jurusan Sekolah", 
                        "Jenis Sekolah",
                        "Jenis Kelas", 
                        "Akreditasi Sekolah", 
                        "Prestasi Sekolah", 
                        "Alumni Sekolah", 
                        "PTN Pilihan I", 
                        "Jurusan Pilihan I di PTN Pilihan I" ,
                        "Jurusan Pilihan II di PTN Pilihan I", 
                        "PTN Pilihan II", 
                        "Jurusan Pilihan I di PTN Pilihan II" ,
                        "Jurusan Pilihan II di PTN Pilihan II", 
                        "Jurusan Diterima", "PTN Diterima", 
                        "Matematika Semester 1", 
                        "Matematika Semester 2", 
                        "Matematika Semester 3", 
                        "Matematika Semester 4", 
                        "Matematika Semester 5", 
                        "Inggris Semester 1", 
                        "Inggris Semester 2", 
                        "Inggris Semester 3", 
                        "Inggris Semester 4", 
                        "Inggris Semester 5",
                        "Indonesia Semester 1",
                        "Indonesia Semester 2",
                        "Indonesia Semester 3",
                        "Indonesia Semester 4",
                        "Indonesia Semester 5",
                        "Fisika Semester 1",
                        "Fisika Semester 2",
                        "Fisika Semester 3",
                        "Fisika Semester 4",
                        "Fisika Semester 5",
                        "Kimia Semester 1",
                        "Kimia Semester 2",
                        "Kimia Semester 3",
                        "Kimia Semester 4",
                        "Kimia Semester 5",
                        "Biologi Semester 1",
                        "Biologi Semester 2",
                        "Biologi Semester 3",
                        "Biologi Semester 4",
                        "Biologi Semester 5",
                        "Ekonomi Semester 1",
                        "Ekonomi Semester 2",
                        "Ekonomi Semester 3",
                        "Ekonomi Semester 4",
                        "Ekonomi Semester 5",
                        "Geografi Semester 1",
                        "Geografi Semester 2",
                        "Geografi Semester 3",
                        "Geografi Semester 4",
                        "Geografi Semester 5",
                        "Sosiologi Semester 1",
                        "Sosiologi Semester 2",
                        "Sosiologi Semester 3",
                        "Sosiologi Semester 4",
                        "Sosiologi Semester 5",
                        "Sejarah Semester 1",
                        "Sejarah Semester 2",
                        "Sejarah Semester 3",
                        "Sejarah Semester 4",
                        "Sejarah Semester 5",
                        "Komputer Semester 1",
                        "Komputer Semester 2",
                        "Komputer Semester 3",
                        "Komputer Semester 4",
                        "Komputer Semester 5",
                        "Peringkat Kelas Semester 1",
                        "Peringkat Kelas Semester 2",
                        "Peringkat Kelas Semester 3",
                        "Peringkat Kelas Semester 4",
                        "Peringkat Kelas Semester 5",
                        "Nilai UN", 
                        "Saran",
                        "Prestasi Lain"
                    ]
    
    #drop column yang tidak digunakan
    data = raw_data.drop([
            "Nama Panggilan", 
            "Asal Sekolah", 
            "Jenis Kelas", 
            "Akreditasi Sekolah",
            "Prestasi Sekolah", 
            "Alumni Sekolah", 
            "PTN Pilihan I", 
            "Jurusan Pilihan I di PTN Pilihan I" ,
            "Jurusan Pilihan II di PTN Pilihan I", 
            "PTN Pilihan II", 
            "Jurusan Pilihan I di PTN Pilihan II" ,
            "Jurusan Pilihan II di PTN Pilihan II", 
            "Komputer Semester 1",
            "Komputer Semester 2",
            "Komputer Semester 3",
            "Komputer Semester 4",
            "Komputer Semester 5",
            "Peringkat Kelas Semester 1",
            "Peringkat Kelas Semester 2",
            "Peringkat Kelas Semester 3",
            "Peringkat Kelas Semester 4",
            "Peringkat Kelas Semester 5",
            "Nilai UN", 
            "Saran",
            "Prestasi Lain"
        ],axis=1)
    
    return data

# Cleaning Nilai

Proses cleaning nilai terdiri dari beberapa langkah:

1. Mengambil nilai tengah dari tiap mata pelajaran
2. Mengganti setiap NaN/null data dengan mean per mata pelajaran

In [3]:
def cleaning_nilai(data):

    #Mengambil nilai tengah dari tiap nilai
    data = data.replace("<70", 34.5)
    data = data.replace("71 - 75", 73)
    data = data.replace("76 - 80", 78)
    data = data.replace("81 - 85", 83)
    data = data.replace("86 - 90", 88)
    data = data.replace("91 - 95", 93)
    data = data.replace("> 95", 98)
    data = data.replace("No data", np.NaN)

    return data

In [4]:
def replace_zero_w_mean(data, mata_pelajaran):
    
    #mencari rata-rata dari per mata pelajaran
    rata2 = (data[f"{mata_pelajaran} Semester 1"].mean() 
            + data[f"{mata_pelajaran} Semester 2"].mean() 
            + data[f"{mata_pelajaran} Semester 3"].mean()
            + data[f"{mata_pelajaran} Semester 4"].mean()
            + data[f"{mata_pelajaran} Semester 5"].mean())/5
    
    #mengganti NaN value dengan nilai rata-rata
    values = {
        f"{mata_pelajaran} Semester 1": rata2,
        f"{mata_pelajaran} Semester 2": rata2,
        f"{mata_pelajaran} Semester 3": rata2,
        f"{mata_pelajaran} Semester 4": rata2,
        f"{mata_pelajaran} Semester 5": rata2,
    }
    data = data.fillna(value=values)
                    
    return data

# Menghitung Rata-Rata Per 5 Semester

Dari nilai-nilai yang telah di-clean kemudian akan dicari rata-rata tiap mata pelajarannya per semester

In [5]:
def rata2_mp_semester(data, mata_pelajaran):
    data_rata2 = {}
    
    #drop column tiap mata pelajaran untuk digantikan dengan rata-rata semester
    mapel = []
    for i in range(1,6):
        mapel.append(f"{mata_pelajaran} Semester {i}")

    data_drop = data.drop(mapel, axis=1)
    
    
    for column in data_drop:
        isi = []
        for i in range(len(data)):
            isi.append(data[column][i])
        data_rata2[column] = isi

    #menghitung rata-rata nilai 5 semester
    mean = []
    for i in range(len(data)):
        jumlah_nilai = 0
        jumlah_nilai += data[f"{mata_pelajaran} Semester 1"][i] + data[f"{mata_pelajaran} Semester 2"][i] + data[f"{mata_pelajaran} Semester 3"][i] + data[f"{mata_pelajaran} Semester 4"][i] + data[f"{mata_pelajaran} Semester 5"][i]
        mean.append(jumlah_nilai/5)

    #memasukkan column rata-rata 5 semester tiap mata pelajaran ke dataframe
    data_rata2[f"Rata-rata {mata_pelajaran}"] = mean

    data_rata2_frame = pd.DataFrame(data=data_rata2)
    
    return data_rata2_frame

# Menghapus NaN

Proses ini akan menghapus tiap rows yang memiliki NaN value yang ada pada column Jurusan Diterima

In [6]:
def remove_nan(data):
    drop_index = []

    #menghapus NaN value
    for i in range(len(data)):
        try:
            float(data["Jurusan Diterima"][i])
        except ValueError:
            pass
        else:
            if math.isnan(float(data["Jurusan Diterima"][i])) or int(data["Jurusan Diterima"][i]) == 0:
                drop_index.append(i)

    data = data.drop(drop_index)
        
    return data

In [7]:
def clean_jurusan_ptn(data):
    for i in range(len(data)):
        for column in data:
            if column == "Jurusan Diterima":
                data[column][i] = data[column][i].title()
            elif column == "PTN Diterima":
                data[column][i] = data[column][i].upper()
    
    return data

In [8]:
def clean(files):
    cleanned_data = []
    
    for file in files:
        data = open_file(file)

        data = cleaning_nilai(data)

        matpel = ["Matematika", "Inggris", "Indonesia", "Fisika", "Kimia", "Biologi", "Ekonomi", "Geografi", "Sosiologi","Sejarah"]

        for item in matpel:
            data = replace_zero_w_mean(data, item)
            data = rata2_mp_semester(data, item)
                    
        data = remove_nan(data)
        
        cleanned_data.append(data)
        
        data_merge = pd.concat(cleanned_data, ignore_index=True)
        
        result = clean_jurusan_ptn(data_merge)

    return result

In [9]:
def sort_data(data):
    data_sort = data.sort_values(by=['Jurusan Diterima', 'PTN Diterima'])
    
    data_sort.reset_index(inplace = True)

    data_sort = data_sort.drop(["index"], axis=1)

    return data_sort

In [10]:
def get_jurusan_ptn(data):
    temp_jurusan = ""
    temp_ptn = ""
    list_jurusan_ptn = []
    for i in range(len(data)):
        if data["Jurusan Diterima"][i] != temp_jurusan and data["PTN Diterima"][i] != temp_ptn:
            temp_jurusan = data["Jurusan Diterima"][i]
            temp_ptn = data["PTN Diterima"][i]
            list_jurusan_ptn.append((temp_jurusan, temp_ptn))
        else:
            pass

    return list_jurusan_ptn

In [11]:
def get_tabel_alternatif(data, list_jurusan_ptn):
    frame = {}
    for j in range(len(list_jurusan_ptn)):
        list_nilai = []
        for column in data:
            jum = 0
            byk = 0
            for i in range(len(data)):
                if data["Jurusan Diterima"][i] == list_jurusan_ptn[j][0] and data["PTN Diterima"][i] == list_jurusan_ptn[j][1]:
    #                 print(data_sort["Jurusan Diterima"][i], data_sort["PTN Diterima"][i])
                    temp_jurusan = data["Jurusan Diterima"][i]
                    temp_ptn = data["PTN Diterima"][i]
                    try:
                        float(data[column][i])
                    except ValueError:
                        break
                    else:
                        jum += data[column][i]
                        byk += 1
                else:
                    pass
            try:
    #             print(column, jum/byk)
                list_nilai.append(jum/byk)
            except ZeroDivisionError:
                continue
        nama_alternatif = f"{temp_jurusan} - {temp_ptn}"
        if "administrasi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "sosial" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "ekonomi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "hi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "hukum" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "komunikasi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "politik" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "sosiologi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "fsrd" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "sbm" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "akuntansi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "manajemen" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "psdk" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "fiskal" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif ("hubungan" and "internasional") in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "kriminologi" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif ("psikologi" and "-" and "ui") in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "bisnis" in temp_jurusan.casefold().split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPS)"
        elif "sastra" in temp_jurusan.casefold().split():
            continue
        elif "bahasa" in temp_jurusan.casefold().split():
            continue
        
        if "(IPS)" not in nama_alternatif.split():
            nama_alternatif = f"{temp_jurusan} - {temp_ptn} (IPA)"
            
        frame[nama_alternatif] = list_nilai

    tabel = pd.DataFrame(frame, index=["Matematika", "Inggris", "Indonesia", "Fisika", "Kimia", "Biologi", "Ekonomi", "Geografi", "Sosiologi", "Sejarah"])

    return tabel

In [12]:
datasets = ["Data SNMPTN 2016 IPB by @halokampus.csv",
            "Data SNMPTN 2016 ITB by @halokampus.csv",
            "Data SNMPTN 2016 ITS by @halokampus.csv",
            "Data SNMPTN 2016 UB by @halokampus.csv",
            "Data SNMPTN 2016 UGM by @halokampus.csv",
            "Data SNMPTN 2016 UI by @halokampus.csv",
            "Data SNMPTN 2016 Unair by @halokampus.csv",
            "Data SNMPTN 2016 Undip by @halokampus.csv",
            "Data SNMPTN 2016 Unpad by @halokampus.csv",]

result = clean(datasets)

data_sort = sort_data(result)

list_jurusan_ptn = get_jurusan_ptn(data_sort)

tabel_alternatif = get_tabel_alternatif(data_sort, list_jurusan_ptn)

tabel_alternatif

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

,Administrasi Fiskal - UI (IPS),Administrasi Perpajakan - UB (IPS),Agribisnis - IPB (IPA),Agroekoteknologi - UB (IPA),Agronomi Dan Holtikultura - IPB (IPA),Agroteknologi - UNPAD (IPA),Akuntansi - UGM (IPS),Akutansi - UI (IPA),Antropologi - UNPAD (IPA),Antropologi Sosial - UB (IPS),...,Teknik Sipil - UB (IPA),Teknik Sipil Dan Lingkungan - IPB (IPA),Teknik Sistem Perkapalan - ITS (IPA),Teknobiomedik - UNAIR (IPA),Teknologi Bioproses - UI (IPA),Teknologi Dan Manajemen Perikanan Budidaya - IPB (IPS),Teknologi Hasil Perikanan - UB (IPA),Teknologi Industri Pertanian - IPB (IPA),Teknologi Pangan - UB (IPA),Teknologi Produksi Ternak - IPB (IPA)
Matematika,84.000000,92.000000,95.000,81.852143,91.000000,86.000000,92.500000,44.693125,84.000000,77.0,...,90.000000,89.0,86.000000,87.733333,85.465625,86.000000,82.000000,84.547599,82.408571,67.500000
Inggris,84.000000,86.000000,90.000,84.729722,91.000000,87.500000,93.000000,54.255467,79.000000,81.0,...,86.000000,87.0,91.000000,87.000000,83.888667,85.000000,91.000000,84.366667,83.918889,67.500000
Indonesia,84.000000,89.000000,88.000,85.837917,89.000000,88.500000,92.000000,85.000000,80.000000,80.0,...,85.000000,89.0,90.000000,87.333333,85.246032,85.000000,89.000000,85.719387,84.351667,70.500000
Fisika,82.000000,81.956615,91.000,81.739154,89.000000,81.000000,89.421732,87.000000,83.198246,73.0,...,85.000000,87.0,93.000000,85.450000,84.493016,84.000000,80.000000,83.413793,81.956615,66.833333
Kimia,81.000000,82.397782,89.000,82.349446,90.000000,84.500000,89.921569,74.300000,85.673434,73.0,...,79.000000,92.0,81.000000,85.537879,85.297674,84.000000,79.000000,84.100000,82.397782,65.500000
Biologi,83.000000,82.827536,90.000,83.706884,91.000000,87.000000,92.029412,83.000000,84.964912,73.0,...,85.000000,92.0,86.000000,86.522727,84.182558,82.000000,83.000000,86.188889,82.827536,67.500000
Ekonomi,86.145714,91.242143,85.000,83.726429,83.000000,82.348946,95.000000,86.145714,80.000000,79.0,...,84.210714,86.0,87.942857,86.097619,86.145714,83.000000,88.726429,84.666667,84.210714,77.200000
Geografi,85.512727,91.000000,81.316,84.627747,83.526667,79.568923,89.697727,85.512727,82.000000,77.0,...,84.808608,86.0,NaN,85.933333,85.512727,83.526667,84.808608,83.526667,84.808608,77.551111
Sosiologi,86.930877,91.000000,NaN,85.702500,NaN,77.560222,92.944444,86.930877,80.000000,83.0,...,84.850000,NaN,NaN,85.366667,86.930877,NaN,84.850000,NaN,84.850000,NaN
Sejarah,83.943883,93.000000,89.000,85.517917,82.676471,80.916340,93.500000,85.000000,81.000000,80.0,...,83.000000,89.0,87.250000,86.600000,83.943883,86.000000,83.000000,84.117647,85.071667,67.166667

In [13]:
nilai_jams = [83.34, 82, 90, 85.2, 82, 83.4, 0, 0, 0, 0]

tabel_alternatif["Threshold"] = nilai_jams

tabel_alternatif

,Administrasi Fiskal - UI (IPS),Administrasi Perpajakan - UB (IPS),Agribisnis - IPB (IPA),Agroekoteknologi - UB (IPA),Agronomi Dan Holtikultura - IPB (IPA),Agroteknologi - UNPAD (IPA),Akuntansi - UGM (IPS),Akutansi - UI (IPA),Antropologi - UNPAD (IPA),Antropologi Sosial - UB (IPS),...,Teknik Sipil Dan Lingkungan - IPB (IPA),Teknik Sistem Perkapalan - ITS (IPA),Teknobiomedik - UNAIR (IPA),Teknologi Bioproses - UI (IPA),Teknologi Dan Manajemen Perikanan Budidaya - IPB (IPS),Teknologi Hasil Perikanan - UB (IPA),Teknologi Industri Pertanian - IPB (IPA),Teknologi Pangan - UB (IPA),Teknologi Produksi Ternak - IPB (IPA),Threshold
Matematika,84.000000,92.000000,95.000,81.852143,91.000000,86.000000,92.500000,44.693125,84.000000,77.0,...,89.0,86.000000,87.733333,85.465625,86.000000,82.000000,84.547599,82.408571,67.500000,83.34
Inggris,84.000000,86.000000,90.000,84.729722,91.000000,87.500000,93.000000,54.255467,79.000000,81.0,...,87.0,91.000000,87.000000,83.888667,85.000000,91.000000,84.366667,83.918889,67.500000,82.00
Indonesia,84.000000,89.000000,88.000,85.837917,89.000000,88.500000,92.000000,85.000000,80.000000,80.0,...,89.0,90.000000,87.333333,85.246032,85.000000,89.000000,85.719387,84.351667,70.500000,90.00
Fisika,82.000000,81.956615,91.000,81.739154,89.000000,81.000000,89.421732,87.000000,83.198246,73.0,...,87.0,93.000000,85.450000,84.493016,84.000000,80.000000,83.413793,81.956615,66.833333,85.20
Kimia,81.000000,82.397782,89.000,82.349446,90.000000,84.500000,89.921569,74.300000,85.673434,73.0,...,92.0,81.000000,85.537879,85.297674,84.000000,79.000000,84.100000,82.397782,65.500000,82.00
Biologi,83.000000,82.827536,90.000,83.706884,91.000000,87.000000,92.029412,83.000000,84.964912,73.0,...,92.0,86.000000,86.522727,84.182558,82.000000,83.000000,86.188889,82.827536,67.500000,83.40
Ekonomi,86.145714,91.242143,85.000,83.726429,83.000000,82.348946,95.000000,86.145714,80.000000,79.0,...,86.0,87.942857,86.097619,86.145714,83.000000,88.726429,84.666667,84.210714,77.200000,0.00
Geografi,85.512727,91.000000,81.316,84.627747,83.526667,79.568923,89.697727,85.512727,82.000000,77.0,...,86.0,NaN,85.933333,85.512727,83.526667,84.808608,83.526667,84.808608,77.551111,0.00
Sosiologi,86.930877,91.000000,NaN,85.702500,NaN,77.560222,92.944444,86.930877,80.000000,83.0,...,NaN,NaN,85.366667,86.930877,NaN,84.850000,NaN,84.850000,NaN,0.00
Sejarah,83.943883,93.000000,89.000,85.517917,82.676471,80.916340,93.500000,85.000000,81.000000,80.0,...,89.0,87.250000,86.600000,83.943883,86.000000,83.000000,84.117647,85.071667,67.166667,0.00

In [114]:
pilihan_jurusan = ["Stei - ITB (IPA)", "Administrasi Fiskal - UI (IPS)", "Akuntansi - UGM (IPS)"]

In [115]:
deviasi = {}
dev_val = {}

# for index_name in tabel_alternatif.index:
#     dev_val[index_name] = 0
    
for jurusan in pilihan_jurusan:
    for jurusan_compare in pilihan_jurusan:
        if jurusan == jurusan_compare:
            continue
        else:
            for index_name in tabel_alternatif.index:
                if "(IPA)" in jurusan.split():
                    if index_name == "Matematika" or index_name == "Inggris" or index_name == "Indonesia" or index_name == "Fisika" or index_name == "Kimia" or index_name == "Biologi":
                        
                        #menghitung deviasi
                        nilai_deviasi = tabel_alternatif[jurusan][index_name] - tabel_alternatif[jurusan_compare][index_name]
                        
                        #menghitung fungsi preferensi gaussian
                        if nilai_deviasi > 0:
                            gaussian = 1 - math.exp(-1*(((nilai_deviasi)**2) / (2*((tabel_alternatif["Threshold"][index_name])**2))))
                        else:
                            gaussian = 0
                            
                        deviasi_name = f"{jurusan}&{jurusan_compare}"
                        dev_val[index_name] = gaussian
                    
                elif "(IPS)" in jurusan.split():
                    if index_name == "Ekonomi" or index_name == "Inggris" or index_name == "Indonesia" or index_name == "Geografi" or index_name == "Sosiologi" or index_name == "Sejarah":
                        
                        #menghitung deviasi
                        nilai_deviasi = tabel_alternatif[jurusan][index_name] - tabel_alternatif[jurusan_compare][index_name]
                        
                        #menghitung fungsi preferensi gaussian
                        if nilai_deviasi > 0:
                            gaussian = 1 - math.exp(-1*(((nilai_deviasi)**2) / (2*((tabel_alternatif["Threshold"][index_name])**2))))
                        else:
                            gaussian = 0
                            
                        deviasi_name = f"{jurusan}&{jurusan_compare}"
                        dev_val[index_name] = gaussian
    
                deviasi[deviasi_name] = dev_val
        dev_val = {}
    
deviasi

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:36: RuntimeWarning: divide by zero encountered in double_scalars

{'Stei - ITB (IPA)&Administrasi Fiskal - UI (IPS)': {'Matematika': 0.001798093523949218,
  'Inggris': 0.0020474623565432948,
  'Indonesia': 0.0005554012631419081,
  'Fisika': 0.002081439645789329,
  'Kimia': 0.00600509736837207,
  'Biologi': 0.0019793670703531774},
 'Stei - ITB (IPA)&Akuntansi - UGM (IPS)': {'Inggris': 0,
  'Indonesia': 0,
  'Ekonomi': 1.0,
  'Geografi': 1.0,
  'Sosiologi': 0,
  'Sejarah': 0},
 'Administrasi Fiskal - UI (IPS)&Stei - ITB (IPA)': {'Inggris': 0,
  'Indonesia': 0,
  'Ekonomi': 0,
  'Geografi': 0,
  'Sosiologi': 0,
  'Sejarah': 0},
 'Administrasi Fiskal - UI (IPS)&Akuntansi - UGM (IPS)': {'Inggris': 0.0010451479790692941,
  'Indonesia': 0.0015420197404703018,
  'Ekonomi': 1.0,
  'Geografi': 1.0,
  'Sosiologi': 0,
  'Sejarah': 1.0},
 'Akuntansi - UGM (IPS)&Stei - ITB (IPA)': {'Inggris': 0.00600509736837207,
  'Indonesia': 0.003942823861809108,
  'Ekonomi': 1.0,
  'Geografi': 1.0,
  'Sosiologi': 1.0,
  'Sejarah': 1.0},
 'Akuntansi - UGM (IPS)&Administrasi Fiskal - UI (IPS)': {'Inggris': 0.00600509736837207,
  'Indonesia': 0.003942823861809108,
  'Ekonomi': 1.0,
  'Geografi': 1.0,
  'Sosiologi': 1.0,
  'Sejarah': 1.0}}

In [116]:
index_preferensi_gaussian = {}
weight = 1

for compare, fgaussian in deviasi.items():
    nilai_gaussian = 0
    for kriteria in fgaussian.keys():
        nilai_gaussian += fgaussian[kriteria]*weight
    nama_gaussian = compare
    index_preferensi_gaussian[nama_gaussian] = nilai_gaussian
    
index_preferensi_gaussian

{'Stei - ITB (IPA)&Administrasi Fiskal - UI (IPS)': 0.014466861228148997,
 'Stei - ITB (IPA)&Akuntansi - UGM (IPS)': 2.0,
 'Administrasi Fiskal - UI (IPS)&Stei - ITB (IPA)': 0,
 'Administrasi Fiskal - UI (IPS)&Akuntansi - UGM (IPS)': 3.0025871677195397,
 'Akuntansi - UGM (IPS)&Stei - ITB (IPA)': 4.009947921230181,
 'Akuntansi - UGM (IPS)&Administrasi Fiskal - UI (IPS)': 4.009947921230181}

In [117]:
entering_flow = {}

for item in pilihan_jurusan:
    ef = 0
    for piece in index_preferensi_gaussian.keys():
        s = piece.split("&")
        
        if item in s and s.index(item) == 1:
            ef += index_preferensi_gaussian[piece] * (1/(len(pilihan_jurusan) - 1))
            
    entering_flow[item] = ef
    
entering_flow

{'Stei - ITB (IPA)': 2.0049739606150907,
 'Administrasi Fiskal - UI (IPS)': 2.012207391229165,
 'Akuntansi - UGM (IPS)': 2.50129358385977}

In [118]:
leaving_flow = {}

for item in pilihan_jurusan:
    lf = 0
    for piece in index_preferensi_gaussian.keys():
        s = piece.split("&")
        
        if item in s and s.index(item) == 0:
            lf += index_preferensi_gaussian[piece] * (1/(len(pilihan_jurusan) - 1))
            
    leaving_flow[item] = lf
    
leaving_flow

{'Stei - ITB (IPA)': 1.0072334306140744,
 'Administrasi Fiskal - UI (IPS)': 1.5012935838597699,
 'Akuntansi - UGM (IPS)': 4.009947921230181}

In [119]:
net_flow = {}

for jurusan in pilihan_jurusan:
    net_flow[jurusan] = entering_flow[jurusan] - leaving_flow[jurusan]
    
net_flow

{'Stei - ITB (IPA)': 0.9977405300010163,
 'Administrasi Fiskal - UI (IPS)': 0.5109138073693953,
 'Akuntansi - UGM (IPS)': -1.5086543373704115}

In [120]:
sorted(net_flow.items(), key = lambda kv:(kv[1], kv[0]), reverse = True)

[('Stei - ITB (IPA)', 0.9977405300010163),
 ('Administrasi Fiskal - UI (IPS)', 0.5109138073693953),
 ('Akuntansi - UGM (IPS)', -1.5086543373704115)]