In [392]:
import pandas as pd

In [393]:
def open_file(file):
    #read dataset
    raw_data = pd.read_csv(file, header=6)

#     #ganti nama header
#     raw_data.columns = [
#                         "Nama Panggilan", 
#                         "Asal Sekolah", 
#                         "Jurusan Sekolah", 
#                         "Jenis Sekolah",
#                         "Jenis Kelas", 
#                         "Akreditasi Sekolah", 
#                         "Prestasi Sekolah", 
#                         "Alumni Sekolah", 
#                         "PTN Pilihan I", 
#                         "Jurusan Pilihan I di PTN Pilihan I" ,
#                         "Jurusan Pilihan II di PTN Pilihan I", 
#                         "PTN Pilihan II", 
#                         "Jurusan Pilihan I di PTN Pilihan II" ,
#                         "Jurusan Pilihan II di PTN Pilihan II", 
#                         "Jurusan Diterima", "PTN Diterima", 
#                         "Matematika Semester 1", 
#                         "Matematika Semester 2", 
#                         "Matematika Semester 3", 
#                         "Matematika Semester 4", 
#                         "Matematika Semester 5", 
#                         "Inggris Semester 1", 
#                         "Inggris Semester 2", 
#                         "Inggris Semester 3", 
#                         "Inggris Semester 4", 
#                         "Inggris Semester 5",
#                         "Indonesia Semester 1",
#                         "Indonesia Semester 2",
#                         "Indonesia Semester 3",
#                         "Indonesia Semester 4",
#                         "Indonesia Semester 5",
#                         "Fisika Semester 1",
#                         "Fisika Semester 2",
#                         "Fisika Semester 3",
#                         "Fisika Semester 4",
#                         "Fisika Semester 5",
#                         "Kimia Semester 1",
#                         "Kimia Semester 2",
#                         "Kimia Semester 3",
#                         "Kimia Semester 4",
#                         "Kimia Semester 5",
#                         "Biologi Semester 1",
#                         "Biologi Semester 2",
#                         "Biologi Semester 3",
#                         "Biologi Semester 4",
#                         "Biologi Semester 5",
#                         "Ekonomi Semester 1",
#                         "Ekonomi Semester 2",
#                         "Ekonomi Semester 3",
#                         "Ekonomi Semester 4",
#                         "Ekonomi Semester 5",
#                         "Geografi Semester 1",
#                         "Geografi Semester 2",
#                         "Geografi Semester 3",
#                         "Geografi Semester 4",
#                         "Geografi Semester 5",
#                         "Sosiologi Semester 1",
#                         "Sosiologi Semester 2",
#                         "Sosiologi Semester 3",
#                         "Sosiologi Semester 4",
#                         "Sosiologi Semester 5",
#                         "Sejarah Semester 1",
#                         "Sejarah Semester 2",
#                         "Sejarah Semester 3",
#                         "Sejarah Semester 4",
#                         "Sejarah Semester 5",
#                         "Komputer Semester 1",
#                         "Komputer Semester 2",
#                         "Komputer Semester 3",
#                         "Komputer Semester 4",
#                         "Komputer Semester 5",
#                     ]
    
#     data = raw_data.drop([
#             "Nama Panggilan", 
#             "Asal Sekolah", 
#             "Jenis Kelas", 
#             "Akreditasi Sekolah",
#             "Prestasi Sekolah", 
#             "Alumni Sekolah", 
#             "PTN Pilihan I", 
#             "Jurusan Pilihan I di PTN Pilihan I" ,
#             "Jurusan Pilihan II di PTN Pilihan I", 
#             "PTN Pilihan II", 
#             "Jurusan Pilihan I di PTN Pilihan II" ,
#             "Jurusan Pilihan II di PTN Pilihan II", 
#             "Komputer Semester 1",
#             "Komputer Semester 2",
#             "Komputer Semester 3",
#             "Komputer Semester 4",
#             "Komputer Semester 5",
#         ],axis=1)
    
    return data

In [394]:
# #drop kolom yang tidak dibutuhkan
# data = raw_data.drop([
#             "Nama Panggilan", 
#             "Asal Sekolah", 
#             "Jenis Kelas", 
#             "Akreditasi Sekolah",
#             "Prestasi Sekolah", 
#             "Alumni Sekolah", 
#             "PTN Pilihan I", 
#             "Jurusan Pilihan I di PTN Pilihan I" ,
#             "Jurusan Pilihan II di PTN Pilihan I", 
#             "PTN Pilihan II", 
#             "Jurusan Pilihan I di PTN Pilihan II" ,
#             "Jurusan Pilihan II di PTN Pilihan II", 
#             "Komputer Semester 1",
#             "Komputer Semester 2",
#             "Komputer Semester 3",
#             "Komputer Semester 4",
#             "Komputer Semester 5",
#         ],axis=1)

In [395]:
def cleaning_nilai(data):
    mp = {
            "Matematika": "Matematika",
            "Inggris": "Inggris",
            "Indonesia": "Indonesia",
            "Fisika": "Fisika",
            "Kimia": "Kimia",
            "Biologi": "Biologi",
            "Ekonomi": "Ekonomi",
            "Geografi": "Geografi",
            "Sosiologi": "Sosiologi",
            "Sejarah": "Sejarah"
        }

    #Mengambil nilai tengah dari tiap nilai
    for column in data:
        matpel = column.split()
        for kata in matpel:
            if kata == mp["Matematika"] or kata == mp["Inggris"] or kata == mp["Indonesia"] or kata == mp["Fisika"] or kata == mp["Kimia"] or kata == mp["Biologi"] or kata == mp["Ekonomi"] or kata == mp["Geografi"] or kata == mp["Sosiologi"] or kata == mp["Sejarah"]:
                for i in range(len(data)):
                    if data[column][i] == "<70":
                        data[column][i] = 69
                    elif data[column][i] == "71 -75":
                        data[column][i] = 73
                    elif data[column][i] == "76 - 80":
                        data[column][i] = 78
                    elif data[column][i] == "81 - 85":
                        data[column][i] = 83
                    elif data[column][i] == "86 - 90":
                        data[column][i] = 88
                    elif data[column][i] == "91 - 95":
                        data[column][i] = 93
                    elif data[column][i] == "> 95":
                        data[column][i] = 96
                    else:
                        data[column][i] = 0

    return data

In [396]:
def replace_zero_w_mean(data, mata_pelajaran):
    jumlah_nilai = 0
    banyak_nilai = 0
    for column in data:
        matpel = column.split()
        for kata in matpel:
            if kata == mp[mata_pelajaran]:
                for i in range(len(data)):
                    if data[column][i] != 0:
                        jumlah_nilai += data[column][i]
                        banyak_nilai += 1

    rata2 = jumlah_nilai/banyak_nilai

    for column in data:
        matpel = column.split()
        for kata in matpel:
            if kata == mp[mata_pelajaran]:
                for i in range(len(data)):
                    if data[column][i] == 0:
                        data[column][i] = rata2
                    
    return data

In [397]:
def rata2_mp_semester(data, mata_pelajaran):
    data_rata2 = {}
    
    mapel = []
    for i in range(1,6):
        mapel.append(f"{mata_pelajaran} Semester {i}")
        
    data_drop = data.drop(mapel, axis=1)

    for column in data_drop:
        isi = []
        for i in range(len(data)):
            header = column
            isi.append(data[column][i])
        data_rata2[column] = isi

    mean = []
    for i in range(len(data)):
        jumlah_nilai = 0
        jumlah_nilai += data[f"{mata_pelajaran} Semester 1"][i] + data[f"{mata_pelajaran} Semester 2"][i] + data[f"{mata_pelajaran} Semester 3"][i] + data[f"{mata_pelajaran} Semester 4"][i] + data[f"{mata_pelajaran} Semester 5"][i]
        mean.append(jumlah_nilai/5)

    data_rata2[f"Rata-rata {mata_pelajaran}"] = mean

    data_rata2_frame = pd.DataFrame(data=data_rata2)
    return data_rata2_frame

In [398]:
# for i in range(len(data_rata2_frame)):
#     data_rata2_frame["PTN Diterima"][i] = data_rata2_frame["PTN Diterima"][i].upper()
#     data_rata2_frame["Jurusan Diterima"][i] = data_rata2_frame["Jurusan Diterima"][i].title()
    
# data_rata2_frame

In [399]:
# def clean(files):
#     cleaned_data = []
    
#     for file in files:
#         data = open_file(file)

#         data = cleaning_nilai(data)

#         matpel = ["Matematika", "Inggris", "Indonesia", "Fisika", "Kimia", "Biologi", "Ekonomi", "Geografi", "Sosiologi","Sejarah"]

#         for item in matpel:
#             data = replace_zero_w_mean(data, item)
#             data = rata2_mp_semester(data, item)
        
#         cleanned_data.append(data)
        
#         result = pd.concat(cleanned_data)

#     return result

In [400]:
# datasets = ["Data SNMPTN 2016 ITB by @halokampus.csv"]

# result = clean(datasets)

# result

data = open_file("Data SNMPTN 2016 ITB by @halokampus.csv")

# matpel = ["Matematika", "Inggris", "Indonesia", "Fisika", "Kimia", "Biologi", "Ekonomi", "Geografi", "Sosiologi","Sejarah"]

# for item in matpel:
#     data = replace_zero_w_mean(data, item)
#     data = rata2_mp_semester(data, item)
    
data

,Jurusan Sekolah,Jenis Sekolah,Jurusan Diterima,PTN Diterima,Rata-rata Matematika,Rata-rata Inggris,Rata-rata Indonesia,Rata-rata Fisika,Rata-rata Kimia,Rata-rata Biologi,Rata-rata Ekonomi,Rata-rata Geografi,Rata-rata Sosiologi,Rata-rata Sejarah
0,IPA,SMA,Kedokteran,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
1,IPA,SMA,Hukum,UNAIR,83.000000,88.6,86.0,83.0,83.0,82.0,86.0,85.0,85.0,86.0
2,IPA,SMA,Kedokteran,Unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
3,IPA,SMA,pendidikan apoteker,unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
4,IPS,SMA,Manajemen,UNAIR,94.200000,90.0,85.0,86.0,86.0,86.0,88.6,83.0,85.0,84.0
5,IPS,SMA,Akuntansi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
6,IPA,SMA,Biologi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
7,IPA,SMA,Kedokteran,UNAIR,93.200000,91.6,94.8,94.8,95.4,95.4,92.0,89.0,87.0,89.0
8,IPS,SMA,Psikologi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
9,IPA,SMA,PSIKOLOGI,UNAIR,88.000000,88.0,88.0,86.0,88.0,88.0,86.0,85.0,85.0,86.0
10,IPS,SMA,Akuntansi,UNAIR,83.954054,80.0,82.0,86.0,86.0,82.8,86.0,81.0,84.0,85.0
11,IPA,SMA,budidaya perairan,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
12,IPS,SMA,Ilmu Komunikasi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
13,IPA,SMA,kesehatan masyarakat,unair,87.000000,84.0,88.0,83.0,81.0,87.0,83.0,85.0,85.0,82.0
14,IPA,SMA,Pendidikan Ners,UNAIR,85.000000,87.0,87.6,87.0,85.0,85.6,84.6,85.0,86.2,90.0
15,IPS,SMA,Psikologi,UNAIR,92.200000,87.0,86.0,86.0,86.0,86.0,83.0,89.0,85.0,89.6
16,IPS,SMA,Psikologi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
17,IPS,SMA,Manajemen,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
18,IPA,SMA,kedokteran hewan,UNAIR,87.000000,85.8,83.8,81.0,81.6,84.0,86.0,85.0,85.0,89.0
19,IPA,SMA,teknobiomedik,Unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
20,IPA,SMA,Pendidikan Dokter,UNAIR,92.000000,90.0,85.0,90.0,86.0,92.0,91.0,85.0,85.0,86.0
21,IPA,SMA,Budidaya perairan,Unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
22,IPS,SMA,akuntansi,unair,85.000000,89.0,87.0,86.0,86.0,86.0,86.0,89.0,84.0,90.0
23,IPA,SMA,Apoteker,Unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
24,IPS,SMA,Hukum,unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
25,IPA,SMA,Pendidikan Apoteker,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
26,IPS,SMA,Hukum,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
27,IPS,SMA,Ilmu Hukum,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
28,IPS,SMA,Akuntansi,Unair,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0
29,IPA,SMA,Sastra Inggris,UNAIR,86.000000,83.0,90.6,82.2,84.2,80.6,82.8,84.4,85.0,82.6
30,IPA,SMA,KESEHATAN MASYARAKAT,UNAIR,86.000000,87.0,91.0,87.0,92.0,89.0,86.0,85.0,85.0,86.0
31,IPA,SMA,KESEHATAN MASYARAKAT,UNAIR,85.000000,85.0,84.0,85.2,83.0,84.0,83.2,85.0,85.0,87.0
32,IPA,SMA,Pendidikan Dokter Gigi,UNAIR,89.000000,91.0,92.0,92.0,93.0,91.0,86.0,85.0,85.0,86.0
33,IPS,SMA,Akuntansi,UNAIR,87.770270,87.0,87.0,86.0,86.0,86.0,86.0,85.0,85.0,86.0